from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import TextIO

from limuzin_grid_manager.core.export_cells import (
    big_tile_fill_color,
    big_tile_number,
    big_tile_placemark_name,
    iter_grid_cells,
    iter_subcells,
    small_number_for_cell,
)
from limuzin_grid_manager.core.export_progress import ProgressTracker
from limuzin_grid_manager.core.models import Bounds, GridOptions, KmlStyle
from limuzin_grid_manager.core.stats import ensure_exportable, estimate_export_placemarks


SVG_NAMESPACE = "http://www.w3.org/2000/svg"


def write_svg_all(
    out_path: Path,
    bounds: Bounds,
    options: GridOptions,
    progress: Callable[[int, int], None] | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> None:
    options = options.normalized()
    stats = ensure_exportable(bounds, options)
    canvas_bounds = stats.big_bounds if options.include_1000 else stats.small_bounds
    if canvas_bounds is None:
        raise ValueError("Нет расчетной области для SVG-экспорта.")

    big_tile_names = dict(options.big_tile_names)
    style = options.kml_style
    zone = stats.zone or 0
    tracker = ProgressTracker(progress, estimate_export_placemarks(stats, options), cancelled)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="\n") as fh:
        _write_svg_start(fh, canvas_bounds, zone)

        if options.include_1000:
            assert stats.big_bounds is not None
            assert stats.big_grid is not None
            _write_big_layer(fh, stats.big_bounds, stats.big_grid.cols, options, big_tile_names, style, zone, tracker)
            if options.include_100:
                _write_small_layer_for_big_tiles(
                    fh,
                    stats.big_bounds,
                    stats.big_grid.cols,
                    options,
                    canvas_bounds,
                    style,
                    zone,
                    tracker,
                )
        else:
            assert stats.small_bounds is not None
            assert stats.small_grid is not None
            _write_small_only_layer(fh, stats.small_bounds, options, canvas_bounds, style, zone, tracker)

        _write_svg_end(fh)
    tracker.finish()


def _write_svg_start(fh: TextIO, bounds: Bounds, zone: int) -> None:
    width = bounds.width_m()
    height = bounds.height_m()
    fh.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    fh.write(
        f'<svg xmlns="{SVG_NAMESPACE}" version="1.1" '
        f'width="{width}mm" height="{height}mm" viewBox="0 0 {width} {height}" '
        f'data-zone="{zone}">\n'
    )
    fh.write("<title>LIMUZIN GRID MANAGER</title>\n")
    fh.write("<desc>Generated by LIMUZIN GRID MANAGER</desc>\n")


def _write_svg_end(fh: TextIO) -> None:
    fh.write("</svg>\n")


def _write_big_layer(
    fh: TextIO,
    bounds: Bounds,
    cols: int,
    options: GridOptions,
    big_tile_names: dict[int, str],
    style: KmlStyle,
    zone: int,
    tracker: ProgressTracker,
) -> None:
    fh.write('<g id="grid-1000" data-layer="1000x1000">\n')
    for row, col, x_top, y_left in iter_grid_cells(bounds, 1000):
        big_num = big_tile_number(row, col, cols, options.snake_big)
        name = big_tile_placemark_name(big_num, big_tile_names)
        _write_rect(
            fh,
            bounds,
            x_top,
            y_left,
            1000,
            1000,
            style.big_line_color,
            style.big_line_width,
            big_tile_fill_color(big_num, style),
            style.big_fill_opacity,
            layer="1000x1000",
            zone=zone,
            big_number=big_num,
        )
        _write_label(fh, bounds, x_top, y_left, 1000, 1000, name, "1000x1000", zone, big_num, None)
        tracker.step()
    fh.write("</g>\n")


def _write_small_layer_for_big_tiles(
    fh: TextIO,
    bounds: Bounds,
    cols: int,
    options: GridOptions,
    canvas_bounds: Bounds,
    style: KmlStyle,
    zone: int,
    tracker: ProgressTracker,
) -> None:
    fh.write('<g id="grid-100" data-layer="100x100">\n')
    for row, col, x_top, y_left in iter_grid_cells(bounds, 1000):
        big_num = big_tile_number(row, col, cols, options.snake_big)
        for small_row, small_col, small_x_top, small_y_left in iter_subcells(x_top, y_left):
            small_num = small_number_for_cell(small_row, small_col, 10, 10, options)
            _write_small_rect_and_label(
                fh,
                canvas_bounds,
                small_x_top,
                small_y_left,
                small_num,
                style,
                zone,
                big_num,
                tracker,
            )
    fh.write("</g>\n")


def _write_small_only_layer(
    fh: TextIO,
    bounds: Bounds,
    options: GridOptions,
    canvas_bounds: Bounds,
    style: KmlStyle,
    zone: int,
    tracker: ProgressTracker,
) -> None:
    fh.write('<g id="grid-100" data-layer="100x100">\n')
    for row, col, x_top, y_left in iter_grid_cells(bounds, 100):
        small_num = small_number_for_cell(row, col, bounds.height_m() // 100, bounds.width_m() // 100, options)
        _write_small_rect_and_label(fh, canvas_bounds, x_top, y_left, small_num, style, zone, None, tracker)
    fh.write("</g>\n")


def _write_small_rect_and_label(
    fh: TextIO,
    canvas_bounds: Bounds,
    x_top: int,
    y_left: int,
    small_num: int,
    style: KmlStyle,
    zone: int,
    big_num: int | None,
    tracker: ProgressTracker,
) -> None:
    _write_rect(
        fh,
        canvas_bounds,
        x_top,
        y_left,
        100,
        100,
        style.small_line_color,
        style.small_line_width,
        style.small_fill_color if style.small_fill_enabled else None,
        style.small_fill_opacity,
        layer="100x100",
        zone=zone,
        big_number=big_num,
        small_number=small_num,
    )
    _write_label(fh, canvas_bounds, x_top, y_left, 100, 100, str(small_num), "100x100", zone, big_num, small_num)
    tracker.step()


def _write_rect(
    fh: TextIO,
    canvas_bounds: Bounds,
    x_top: int,
    y_left: int,
    step_x: int,
    step_y: int,
    line_color: str,
    line_width: int,
    fill_color: str | None,
    fill_opacity: int,
    *,
    layer: str,
    zone: int,
    big_number: int | None = None,
    small_number: int | None = None,
) -> None:
    x, y = _svg_xy(canvas_bounds, x_top, y_left)
    attrs = [
        f'x="{x:g}"',
        f'y="{y:g}"',
        f'width="{step_y:g}"',
        f'height="{step_x:g}"',
        _fill_attrs(fill_color, fill_opacity),
        f'stroke="{line_color}"',
        f'stroke-width="{int(line_width)}"',
        'vector-effect="non-scaling-stroke"',
        f'data-layer="{escape_xml(layer)}"',
        f'data-zone="{zone}"',
    ]
    if big_number is not None:
        attrs.append(f'data-big-number="{big_number}"')
    if small_number is not None:
        attrs.append(f'data-small-number="{small_number}"')
    fh.write(f"<rect {' '.join(attrs)} />\n")


def _write_label(
    fh: TextIO,
    canvas_bounds: Bounds,
    x_top: int,
    y_left: int,
    step_x: int,
    step_y: int,
    text: str,
    layer: str,
    zone: int,
    big_number: int | None,
    small_number: int | None,
) -> None:
    x, y = _svg_xy(canvas_bounds, x_top, y_left)
    font_size = 140 if step_x >= 1000 else 28
    attrs = [
        f'x="{x + step_y / 2:g}"',
        f'y="{y + step_x / 2:g}"',
        f'font-size="{font_size}"',
        'font-family="Arial, sans-serif"',
        'text-anchor="middle"',
        'dominant-baseline="central"',
        'fill="#111111"',
        'pointer-events="none"',
        f'data-layer="{escape_xml(layer)}"',
        f'data-zone="{zone}"',
    ]
    if big_number is not None:
        attrs.append(f'data-big-number="{big_number}"')
    if small_number is not None:
        attrs.append(f'data-small-number="{small_number}"')
    fh.write(f"<text {' '.join(attrs)}>{escape_xml(text)}</text>\n")


def _svg_xy(bounds: Bounds, x_top: int, y_left: int) -> tuple[float, float]:
    return float(y_left - bounds.y_left), float(bounds.x_top - x_top)


def _fill_attrs(fill_color: str | None, fill_opacity: int) -> str:
    if fill_color is None or fill_opacity <= 0:
        return 'fill="none"'
    opacity = max(0, min(100, int(fill_opacity))) / 100
    return f'fill="{fill_color}" fill-opacity="{opacity:g}"'


def escape_xml(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )
